### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by miguelrk** [netzo/netzo#18]
This issue exists as a continually growing roadmap. In general, there should be 3 ways of deploying a project in implementation order:

- [x] **1. Deploy within Netzo:** enable quick edits and simple deployments (alpha: not the best DX in editor)
- [x] **2. Deploy with `netzo/cli`:** enables local development and manual deployment via `netzo deploy`
- [ ] **3. Deploy with Github integration:** enables automatic deployment and source control via GitHub
  - [ ] **3a. Automatic:** link a repo+branch in app, set up webhook in github, and let api listen to new commits on push
  - [ ] **3b. Github Action:** ability to customize deployment with additional steps in workflow (advanced)

```[tasklist]
### `netzo/cli`
- [ ] #11
- [ ] #12
- [ ] #13
- [ ] #14
- [ ] #15
```

```[tasklist]
### `netzo/lib`
- [ ] #9 
- [ ] #10
- [ ] #16
```

```[tasklist]
### DevOps
- [ ] #17
```

**Comment by miguelrk** [comment]
Closing to track using GitHub projects
