### ISSUE TITLE
[platform] update sidebar help links

### ISSUE THREAD

**Issue by gabrielromk** [netzo/netzo#73]
```[tasklist]
### Tasks
- [x] remove walkthrough video (comment out)
- [x] update Documentation link (`https://netzo.io/docs/get-started/overview` -> to `https://netzo.io/docs`)
- [x] update links under user settings
```

**Comment by miguelrk** [comment]
Cosing as done.
