### ISSUE TITLE
[platform] update legal links

### ISSUE THREAD

**Issue by gabrielromk** [netzo/netzo#74]
```[tasklist]
### Tasks
- [x] Update Terms and Conditions (`https://netzo.io/legal/agreements-and-terms/main-services-agreement`)
- [x] Update Privacy Policy (`https://netzo.io/legal/policies/privacy-policy`)
- [x] Add Fair Use Policy (`https://netzo.io/legal/policies/fair-use-policy`)
- [x] Add Security Policy (`https://netzo.io/legal/policies/security-policy`)
```

**Comment by miguelrk** [comment]
Closing as completed.
